spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
        instance:
          name: library-api

logging:
  file: app.log

management:
  endpoints:
    web:
      exposure:
        include: "*"