spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
        instance:
          name: library-api

logging:
  file: app.log

management:
  endpoints:
    web:
      exposure:
        include: "*"

java:
  runtime:
    version: zulu-1.13.0.0

maven:
  version: 3.6.2